// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/video/transcoder/v1beta1/resources.proto

package com.google.cloud.video.transcoder.v1beta1;

public interface FailureDetailOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.video.transcoder.v1beta1.FailureDetail)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * A description of the failure.
   * </pre>
   *
   * <code>string description = 1;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <pre>
   * A description of the failure.
   * </pre>
   *
   * <code>string description = 1;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();
}
