// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/video/transcoder/v1beta1/services.proto

package com.google.cloud.video.transcoder.v1beta1;

public interface ListJobsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.video.transcoder.v1beta1.ListJobsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * List of jobs in the specified region.
   * </pre>
   *
   * <code>repeated .google.cloud.video.transcoder.v1beta1.Job jobs = 1;</code>
   */
  java.util.List<com.google.cloud.video.transcoder.v1beta1.Job> 
      getJobsList();
  /**
   * <pre>
   * List of jobs in the specified region.
   * </pre>
   *
   * <code>repeated .google.cloud.video.transcoder.v1beta1.Job jobs = 1;</code>
   */
  com.google.cloud.video.transcoder.v1beta1.Job getJobs(int index);
  /**
   * <pre>
   * List of jobs in the specified region.
   * </pre>
   *
   * <code>repeated .google.cloud.video.transcoder.v1beta1.Job jobs = 1;</code>
   */
  int getJobsCount();
  /**
   * <pre>
   * List of jobs in the specified region.
   * </pre>
   *
   * <code>repeated .google.cloud.video.transcoder.v1beta1.Job jobs = 1;</code>
   */
  java.util.List<? extends com.google.cloud.video.transcoder.v1beta1.JobOrBuilder> 
      getJobsOrBuilderList();
  /**
   * <pre>
   * List of jobs in the specified region.
   * </pre>
   *
   * <code>repeated .google.cloud.video.transcoder.v1beta1.Job jobs = 1;</code>
   */
  com.google.cloud.video.transcoder.v1beta1.JobOrBuilder getJobsOrBuilder(
      int index);

  /**
   * <pre>
   * The pagination token.
   * </pre>
   *
   * <code>string next_page_token = 2;</code>
   * @return The nextPageToken.
   */
  java.lang.String getNextPageToken();
  /**
   * <pre>
   * The pagination token.
   * </pre>
   *
   * <code>string next_page_token = 2;</code>
   * @return The bytes for nextPageToken.
   */
  com.google.protobuf.ByteString
      getNextPageTokenBytes();
}
