// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/video/transcoder/v1beta1/resources.proto

package com.google.cloud.video.transcoder.v1beta1;

public interface OutputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.video.transcoder.v1beta1.Output)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * URI for the output file(s). For example, `gs://my-bucket/outputs/`.
   * If empty the value is populated from `Job.output_uri`.
   * </pre>
   *
   * <code>string uri = 1;</code>
   * @return The uri.
   */
  java.lang.String getUri();
  /**
   * <pre>
   * URI for the output file(s). For example, `gs://my-bucket/outputs/`.
   * If empty the value is populated from `Job.output_uri`.
   * </pre>
   *
   * <code>string uri = 1;</code>
   * @return The bytes for uri.
   */
  com.google.protobuf.ByteString
      getUriBytes();
}
