// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/video/transcoder/v1beta1/resources.proto

package com.google.cloud.video.transcoder.v1beta1;

public interface ProgressOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.video.transcoder.v1beta1.Progress)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Estimated fractional progress for `analyzing` step.
   * </pre>
   *
   * <code>double analyzed = 1;</code>
   * @return The analyzed.
   */
  double getAnalyzed();

  /**
   * <pre>
   * Estimated fractional progress for `encoding` step.
   * </pre>
   *
   * <code>double encoded = 2;</code>
   * @return The encoded.
   */
  double getEncoded();

  /**
   * <pre>
   * Estimated fractional progress for `uploading` step.
   * </pre>
   *
   * <code>double uploaded = 3;</code>
   * @return The uploaded.
   */
  double getUploaded();

  /**
   * <pre>
   * Estimated fractional progress for `notifying` step.
   * </pre>
   *
   * <code>double notified = 4;</code>
   * @return The notified.
   */
  double getNotified();
}
