// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/video/transcoder/v1beta1/resources.proto

package com.google.cloud.video.transcoder.v1beta1;

public interface SegmentSettingsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.video.transcoder.v1beta1.SegmentSettings)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Duration of the segments in seconds. The default is `"6.0s"`.
   * </pre>
   *
   * <code>.google.protobuf.Duration segment_duration = 1;</code>
   * @return Whether the segmentDuration field is set.
   */
  boolean hasSegmentDuration();
  /**
   * <pre>
   * Duration of the segments in seconds. The default is `"6.0s"`.
   * </pre>
   *
   * <code>.google.protobuf.Duration segment_duration = 1;</code>
   * @return The segmentDuration.
   */
  com.google.protobuf.Duration getSegmentDuration();
  /**
   * <pre>
   * Duration of the segments in seconds. The default is `"6.0s"`.
   * </pre>
   *
   * <code>.google.protobuf.Duration segment_duration = 1;</code>
   */
  com.google.protobuf.DurationOrBuilder getSegmentDurationOrBuilder();

  /**
   * <pre>
   * Required. Create an individual segment file. The default is `false`.
   * </pre>
   *
   * <code>bool individual_segments = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The individualSegments.
   */
  boolean getIndividualSegments();
}
